apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gs-rest-service-{{.Release.Name}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gs-rest-service-{{.Release.Name}}
    spec:
      containers:
      - name: gs-rest-service-{{.Release.Name}}
        image: 'avengersx.azurecr.io/gs-rest-service:latest'
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: {{ .Values.title }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 80
  selector:
    app: gs-rest-service-{{.Release.Name}}